spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages
  mail:
    # 邮件服务地址
    host: smtp.163.com
    # 端口,可不写默认
    port: 25
    # 编码格式
    default-encoding: UTF-8
    # 用户名
    username: abalone_gyblog@163.com
    # 授权码，
    password: JPFJXUDQGYTSDMRM
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 50000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 50000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 50000